2017-06-20 17:40:22 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: expected a dictionary @ data['condition'][0]. Got None
extra keys not allowed @ data['action'][0]['message']. Got None. (See C:\Users\RGonzalez\AppData\Roaming\.homeassistant\configuration.yaml, line 124). Please check the docs at https://home-assistant.io/components/automation/
2017-06-20 17:40:24 ERROR (<concurrent.futures.thread.ThreadPoolExecutor object at 0x0000000003D66EB8>_8) [homeassistant.util.package] Unable to install package zeroconf==0.19.0: Command "c:\users\rgonzalez\appdata\local\programs\python\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\RGONZA~1\\AppData\\Local\\Temp\\pip-build-mt9ix_uj\\netifaces\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\RGONZA~1\AppData\Local\Temp\pip-8647qa60-record\install-record.txt --single-version-externally-managed --compile --home=C:\Users\RGONZA~1\AppData\Local\Temp\tmp720w1ar9" failed with error code 1 in C:\Users\RGONZA~1\AppData\Local\Temp\pip-build-mt9ix_uj\netifaces\
2017-06-20 17:40:24 ERROR (MainThread) [homeassistant.setup] Not initializing zeroconf because could not install dependency zeroconf==0.19.0
2017-06-20 17:40:24 ERROR (MainThread) [homeassistant.setup] Setup failed for zeroconf: Could not install all requirements.
2017-06-20 17:40:26 ERROR (<concurrent.futures.thread.ThreadPoolExecutor object at 0x0000000003D66EB8>_0) [pyicloud.base.http] Misdirected Request
2017-06-20 17:40:26 ERROR (<concurrent.futures.thread.ThreadPoolExecutor object at 0x0000000003D66EB8>_0) [homeassistant.components.device_tracker.icloud] Error logging into iCloud Service: ('Invalid email/password combination.', PyiCloudAPIResponseError('Misdirected Request',))
2017-06-20 17:40:26 ERROR (<concurrent.futures.thread.ThreadPoolExecutor object at 0x0000000003D66EB8>_0) [homeassistant.components.device_tracker.icloud] No ICLOUDTRACKERS added
2017-06-20 17:40:26 ERROR (MainThread) [homeassistant.components.device_tracker] Error setting up platform icloud
2017-06-20 17:40:26 ERROR (MainThread) [homeassistant.setup] Unable to setup dependencies of ios. Setup failed for dependencies: zeroconf
2017-06-20 17:40:26 ERROR (MainThread) [homeassistant.setup] Setup failed for ios: Could not setup all dependencies.
2017-06-20 17:40:55 ERROR (<concurrent.futures.thread.ThreadPoolExecutor object at 0x0000000003D66EB8>_5) [pyicloud.base.http] Misdirected Request
2017-06-20 17:40:55 ERROR (<concurrent.futures.thread.ThreadPoolExecutor object at 0x0000000003D66EB8>_5) [homeassistant.components.device_tracker.icloud] Error logging into iCloud Service: ('Invalid email/password combination.', PyiCloudAPIResponseError('Misdirected Request',))
2017-06-20 17:41:28 WARNING (MainThread) [homeassistant.core] Unable to find service notify/telegram
2017-06-20 17:41:56 ERROR (<concurrent.futures.thread.ThreadPoolExecutor object at 0x0000000003D66EB8>_2) [pyicloud.base.http] Misdirected Request
2017-06-20 17:41:56 ERROR (<concurrent.futures.thread.ThreadPoolExecutor object at 0x0000000003D66EB8>_2) [homeassistant.components.device_tracker.icloud] Error logging into iCloud Service: ('Invalid email/password combination.', PyiCloudAPIResponseError('Misdirected Request',))
2017-06-20 17:42:55 ERROR (<concurrent.futures.thread.ThreadPoolExecutor object at 0x0000000003D66EB8>_7) [pyicloud.base.http] Misdirected Request
2017-06-20 17:42:55 ERROR (<concurrent.futures.thread.ThreadPoolExecutor object at 0x0000000003D66EB8>_7) [homeassistant.components.device_tracker.icloud] Error logging into iCloud Service: ('Invalid email/password combination.', PyiCloudAPIResponseError('Misdirected Request',))
